### ISSUE TITLE
App bug

### ISSUE THREAD

**Issue by Sami32** [Dynamsoft/barcode-reader-mobile-samples#24]
While scanning a basic QR code an error stop the process (Barcode Scanner X v.9.4.0 & Android 7.0 MIUI 11):
`[Attention(exceptionCode:-10004)] *ttps:/**emp**l.**m/u*16*b*rti*a*ta-c6691f***0/`

![Screenshot_2023-01-08-23-31-22-378_com dynamsoft demo dynamsoftbarcodereaderdemo](https://user-images.githubusercontent.com/18471069/211222686-d252ad68-4d17-4a6f-863c-9279aff3f05e.jpg)

**Comment by Dynamsoft-Jerson** [comment]
Thanks for your feedback. Is it possible to learn more about your case?
1)Is the App set to allow networking？
2)Has the App ever worked properly?
3)Is Barcode X v9.4.0 installed directly or upgraded from an older version? Which version?

**Comment by Sami32** [comment]
1) Network not allowed
2) The version before worked correctly
3) It has been upgraded from the precedent version just before

Following your questions i've allowed network then disabled it and your Android application worked correctly.

It seem that a sneaky bug is around.

**Comment by Dynamsoft-Jerson** [comment]
This problem should be caused by the App not being able to connect to the Internet. The Barcode X App need to periodically obtain a valid license from the Dynamsoft License Server.

**Comment by Sami32** [comment]
Oh i see, i've no idea what the period lenght is though.

Then i suggest that your error handling message should be enhanced and more meaningful for your customers.
